[package]
name = "f-init"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
flib = { path = "../flib/" , features = ["real"]}

[profile.release]
opt-level = "z"
